[mysql]
# address = "50.18.79.42"
address = "127.0.0.1"
port = "3306"
db_name = "pledge_v21"
user_name = "root"
password = "ZAqbXlUeg0nnmWRXzyLbhSc9AXuZh4m9"
max_open_conns = 0
max_idle_conns = 0
max_life_time = 0

[redis]
# address = "50.18.79.42"
address = "127.0.0.1"
port = "6379"
db = 1
user_name = ""
password = "pledger_web3"
max_idle = 0
max_active = 0
idle_timeout = 0
